AWSTemplateFormatVersion: 2010-09-09

Parameters: 
  NumberOfAZs:
    Type: Number
    AllowedValues: 
    - 1
    - 2
    - 3
    Default: 2
    Description:  How many Availability Zones do you wish to utilize?
  EnvType:
    Type: String
    AllowedValues:
    - dev
    - test
    - prod
    Default:  dev
    Description: enviornment type 

  UseNAT: 
    Description: Whether to use NAT device or not
    Type: String
    AllowedValues:
    - True
    - False
    Default: False

  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues: [t2.micro]
    ConstraintDescription: must be a valid EC2 instance type.
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    Default: general
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Resources: 
  VPC:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        NumberOfAZs: !Ref NumberOfAZs
        EnvType: !Ref EnvType
      TemplateURL: https://kin-cft-bucket.s3.ap-northeast-2.amazonaws.com/vpc.cfn.yaml
      TimeoutInMinutes: 30
  ASG:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        WebVPC:  !GetAtt VPC.Outputs.VPC
        PublicSubnetA: !GetAtt VPC.Outputs.PublicSubnetA
        PublicSubnetB: !GetAtt VPC.Outputs.PublicSubnetB
        EnvType: !Ref EnvType
      TemplateURL: https://kin-cft-bucket.s3.ap-northeast-2.amazonaws.com/autoscaling.cfn.yaml
      TimeoutInMinutes: 30
    